[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/account"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/article/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"
